name: Java CI/CD Workflow (Without Maven)

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Use Java 11 or your preferred version
        distribution: 'temurin' 

    - name: Run Java Application
      run: |
        javac *.java 
        java MainClass # Replace MainClass with the name of your main class
